### ISSUE TITLE
Use react vega instead of altair?

### ISSUE THREAD

**Issue by PeterSulcs** [changer666666/capstone_frontend_react#3]
https://github.com/vega/react-vega

**Comment by changer666666** [comment]
Chengyang and I discuss react vega a week ago. I think he already has done some research for it. @cabbage-bao

**Comment by changer666666** [comment]
> https://github.com/vega/react-vega

Hi Pete, I have already added this vega react template into our react app. It can show the sample data table in your given repo~ 
P.S. This vega react project also uses a new tool, named "storybook". Seems really cool~
